const words = [
    "abacate", "abacaxi", "abelha", "abismo", "abóbora", "abril", "ácaro", "ácido", "adeus", "ágata",
    "ágil", "água", "agulha", "álamo", "alface", "alho", "aliança", "alma", "alvo", "amarelo",
    "ameixa", "amiga", "amigo", "amor", "amuleto", "anão", "ancião", "anjo", "anotação", "antena",
    "antigo", "apartamento", "apego", "apito", "aprendiz", "aranha", "árduo", "areia", "arma", "arquivo",
    "asa", "áspide", "átila", "átomo", "atraso", "audaz", "áureo", "aurora", "autêntico", "avô",
    "avião", "axila", "azul", "azedo", "azedume", "azeite", "babuíno", "bacalhau", "bagagem", "bailarina",
    "baioneta", "bala", "balança", "baleia", "balé", "bambu", "banana", "bandeira", "banho", "banquete",
    "bar", "baralho", "barata", "barco", "barriga", "batalha", "batata", "bateria", "batida", "batom",
    "beber", "beijo", "beira", "belo", "bengala", "berinjela", "berço", "bife", "bigode", "bílis",
    "biscoito", "bispo", "bisturi", "bitola", "bizarro", "boato", "boca", "boceta", "bode", "bola",
    "bolacha", "bolha", "bolo", "bolota", "bomba", "boneca", "borboleta", "borracha", "bosque", "bota",
    "botão", "bravo", "breve", "brigadeiro", "brilho", "brinco", "broa", "broca", "bronze", "broto",
    "bruma", "bruxa", "buraco", "burro", "cabelo", "cachorro", "cacto", "cadeira", "café", "caixa",
    "caju", "calça", "caldeirão", "caldo", "calha", "calor", "calota", "calça", "calvário", "calçada",
    "cama", "câmera", "camelo", "camisa", "campanha", "canal", "caneta", "canibal", "cano", "canto",
    "capa", "capacete", "capacho", "capela", "capital", "capítulo", "capote", "capricho", "captura", "caráter",
    "caravana", "caravela", "carboidrato", "carcaça", "cardeal", "carinho", "carne", "caroço", "carpa", "carro",
    "carta", "cartão", "carteira", "carvalho", "casa", "casaco", "casamento", "casca", "cascalho", "casebre",
    "cavalo", "caverna", "caviar", "cebola", "cedro", "celeiro", "celular", "cena", "cenário", "censura",
    "centelha", "centro", "cera", "cerca", "cerveja", "cesta", "chácara", "chá", "chaleira", "chama",
    "chaminé", "champagne", "chance", "chapéu", "charme", "chave", "cheiro", "chiclete", "chifre", "chinelo",
    "chocolate", "choque", "choro", "chuva", "ciclo", "cidade", "cigarro", "cilada", "cimento", "cinto",
    "circo", "círculo", "cirurgia", "cisma", "código", "coelho", "cofre", "cogumelo", "cola", "colar",
    "coleção", "colete", "colina", "colônia", "coluna", "comboio", "cometa", "comida", "comitiva", "comoção",
    "companhia", "compasso", "compota", "compra", "comunidade", "computador", "comunismo", "concha", "concreto", "conde",
    "cone", "conexão", "confusão", "conhaque", "conquista", "conselho", "conta", "contato", "conto", "contorno",
    "conversa", "coração", "corda", "corno", "coroa", "corpo", "correio", "corrida", "corrupção", "cortejo",
    "coruja", "costa", "costela", "coxa", "crachá", "cruz", "cruzeiro", "cuia", "culatra", "culpa",
    "cultura", "cura", "curva", "dado", "daltonismo", "dama", "dança", "dardo", "data", "dádiva",
    "dedo", "defesa", "defunto", "degrau", "delícia", "dente", "deputado", "depressão", "deriva", "descarga",
    "descanso", "desenho", "deserto", "desfile", "desgosto", "despejo", "destino", "deus", "deusa", "dia",
    "diamante", "dica", "diálogo", "dicionário", "diesel", "diferença", "difusão", "dignidade", "dilema", "dinheiro",
    "dinossauro", "direito", "diretoria", "discurso", "disfarce", "disfarce", "dispensa", "disposição", "distância", "distribuição",
    "divisão", "dobro", "doca", "doce", "doido", "dois", "dolomita", "dom", "domínio"];

export default words;
